# Read random, writes 5%

replicas: ["10.10.1.3:9305", "10.10.1.4:9304", "10.10.1.5:9303"]

# Number of keys to generate
num_keys: 1024

# one of [random, read_recent, read_modify_update, read_range]
# read range reads 8 entries at once
mode: read_recent

# Proportion of write operations
write_prop: 0

# Contiguous range of keys to scan
# Applicable only in mode read_range
range_scan_num_keys: 8
